### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Prom3thean** [karlstroetmann/Logic#32]
Ich glaube ich habe hier einen Tippfehler gefunden. Sollte es nicht "first(T) = last(S)" heißen?
<img width="482" alt="Typo" src="https://user-images.githubusercontent.com/37518034/70053665-32577b00-15d6-11ea-9716-4c89ff57439a.PNG">

**Comment by karlstroetmann** [comment]
Vielen Dank, ich habe den Fehler korrigiert.
